---
- name: apt-get python-mysqldb
  sudo: true
  apt: pkg=python-mysqldb state=latest
- name: clear omeka user
  mysql_user: name={{db_username}} state=absent
- name: create omeka user
  mysql_user: name={{db_username}} password={{db_password}} state=present priv=*.*:ALL
- name: create omeka db
  mysql_db: name=omeka login_user={{db_username}} login_password={{db_password}} state=present
