---
- name: git clone omeka
  git: repo=https://github.com/omeka/Omeka.git
       dest={{ omekadir }}
  sudo: true
- name: db.ini
  template: src=db.ini.j2 dest={{ omekadir }}/db.ini
  sudo: true
- name: chmod db.ini
  file: path={{ omekadir }}/db.ini mode=0666
  sudo: true
- name: cp config.ini
  command: cp {{ omekadir }}/application/config/config.ini.changeme {{ omekadir }}/application/config/config.ini
  sudo: true
- name: config.ini debug
  ini_file: dest={{ omekadir }}/application/config/config.ini
            section=site
            option=debug.exceptions
            value={{ debug }}
  sudo: true
- name: cp tests/config.ini
  command: cp {{ omekadir }}/application/tests/config.ini.changeme {{ omekadir }}/application/tests/config.ini
  sudo: true
- name: tests/config.ini db.username
  ini_file: dest={{ omekadir }}/application/tests/config.ini
            section=testing
            option=db.username
            value=omeka
  sudo: true
- name: tests/config.ini db.password
  ini_file: dest={{ omekadir }}/application/tests/config.ini
            section=testing
            option=db.password
            value=omeka
  sudo: true
- name: tests/config.ini db.dbname
  ini_file: dest={{ omekadir }}/application/tests/config.ini
            section=testing
            option=db.dbname
            value=omeka
  sudo: true
- name: .htaccess
  command: cp {{ omekadir }}/.htaccess.changeme {{ omekadir }}/.htaccess
  sudo: true
- name: APPLICATION_ENV
  lineinfile: dest={{ omekadir }}/.htaccess
              backrefs=yes
              regexp='# (SetEnv APPLICATION_ENV .*)'
              line='\1'
  sudo: true

- name: create_download_dir
  file: state=directory path={{ plugin_dir }}

- name: download_neatline
  get_url: url={{ neatline_url }} dest={{ plugin_dir }}/neatline.zip

- name: download_neatline_features
  get_url: url={{ nl_features_url }} dest={{ plugin_dir }}/features.zip

- name: download_neatline_maps
  get_url: url={{ nl_maps_url }} dest={{ plugin_dir }}/maps.zip

- name: download_neatline_simile
  get_url: url={{ nl_simile_url }} dest={{ plugin_dir }}/simile.zip
  
- name: download_neatline_time
  get_url: url={{ nl_time_url }} dest={{ plugin_dir }}/time.zip
  
- name: download_neatline_text
  get_url: url={{ nl_text_url }} dest={{ plugin_dir }}/text.zip

- name: download_neatline_waypoints
  get_url: url={{ nl_waypoints_url }} dest={{ plugin_dir }}/waypoints.zip

- name: download_dropbox
  get_url: url={{ dropbox_url }} dest={{ plugin_dir }}/dropbox.zip
  
- name: download_csv
  get_url: url={{ csv_import_url }} dest={{ plugin_dir }}/csv.zip
  
- name: unzip_plugins 
  command: unzip -o {{ plugin_dir }}/\*.zip -d {{omekadir}}/plugins
  sudo: true
  

- name: files
  file: path={{ omekadir }}/files recurse=yes mode=0777
  sudo: true
- name: hostname
  lineinfile: line='127.0.0.1        {{ hostname }}' state=present insertafter=EOF dest=/etc/hosts
  sudo: true
  when: hostname is defined


